### ISSUE TITLE
libarchive 7z / PPMD issue fixed after v3.6.0

### ISSUE THREAD

**Issue by RichardBean** [rwinlib/libarchive#1]
On the libarchive github someone kindly fixed a bug in PPMD extraction - https://github.com/libarchive/libarchive/issues/1497

I've been able to kludge this back into the R archive package, without facing any issues (built under mingw64 and copied libarchive_static.a over libarchive.a in the x64 directory, then built with R CMD INSTALL etc).

Is it possible the zip here could be rebuilt as a new version so that bugs like the PPMD one can now be fixed for others? Thanks.

**Comment by jeroen** [comment]
We build these binaries using: https://github.com/r-windows/rtools-packages. You can send a pull request there. 

Note that we had to [downgrade](https://github.com/r-windows/rtools-packages/commit/a8481cd7078d9675d12ad8b41de2095e0ed1788e) because libarchive 3.5.2 would crash on 32-bit and be super slow on 64-bit. So if you propose an upgrade, please make sure you run `R CMD check` on the archive R package, and check for performance regressions.
